### PR TITLE
Add EXT-X-I-FRAME-STREAM-INF m3u8 tokenization

### PR DESCRIPTION
**Pull request by vs-adm**
Fix EXT-X-I-FRAME-STREAM-INF tags are not being tokenized

### CODE REVIEW

**Comment by erankor** [comment]
Thanks @vs-adm, please update the sizeof as well, it's currently comparing only 'EXT-X-I-FRA'

**Comment by vs-adm** [comment]
@erankor OOPS, sorry, missed it. Please check if it is OK now and I'll squash the branch.

**Comment by erankor** [comment]
Yes, looks good

**Comment by vs-adm** [comment]
Squashed.

**Comment by erankor** [comment]
Thanks, merged

**Pull request merged**
